services:
  ai-ops:
    build:
      context: .
      args:
        USE_OLLAMA: "false"
        USE_CUDA: "false"
        USE_SLIM: "false"
    image: ai-ops:latest
    container_name: ai-ops
    volumes:
      - ai-ops-data:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ai-ops-data: {}
